name: Create Release with Remote Binary

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: Download Binary
        run: |
          # Fetch the remote binary
          curl -L -o logioptionsplus_installer_offline.zip "https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer_offline.zip"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Logi Options+ Installer v${{ github.ref_name }}"
          body: |
            This release includes the Logi Options+ offline installer fetched from the official Logitech server.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: logioptionsplus_installer_offline.zip
          asset_name: logioptionsplus_installer_offline.zip
          asset_content_type: application/zip
